server:
  port: 8383

spring:
  application:
    name: user-service

  cloud:
    consul:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-path: "/actuator/health"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
application:
  jwt:
    secret: "3st3ll3_4nd_s3b"
    expires: 86400000
    prefix: "Bearer "
    header: "Authorization"