spring:
  application:
    name: gateway2-service

  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: to-booking
          uri: lb://booking-service
          predicates:
            - Path=/bookings
            - Method=POST
        - id: to-booking-invoiced
          uri: lb://booking-service
          predicates:
            - Path=/bookings/invoiced
            - Method=GET
