server:
  port: 8181
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:rabbitdb
    username: user
    password: pass
  h2:
    console:
      enabled: true
      path: /h2