spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:invoicedb
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2
