server:
  port: 8282
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:invoicedb
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2

  application:
    name: invoice-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

    stream:
      function:
        definition: processor
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
        bindings:
          # get unprocessed and send processed
          processor-in-0:
            destination: queue.log.messages
            binder: rabbit
            group: unprocessed
          processor-out-0:
            destination: queue.processed.log.messages
            binder: rabbit
            group: processed

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics